site_name: pytorch-symbolic
repo_url: https://github.com/gahaalt/pytorch-symbolic

nav:
    - README: README.md
    - quick_start.md
    - advanced_topics.md
    - benchmarks.md
    - Reference:
        - Reference/symbolic_model.md
        - Reference/symbolic_data.md
        - Reference/add_to_graph.md
        - Reference/graph_algorithms.md
        - Reference/model_tools.md
        - Reference/optimize_module_calls.md
        - Reference/useful_layers.md

copyright:
    Copyright @ 2022 Szymon Mikler

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/szymon-mikler/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/gahaalternative
        - icon: fontawesome/brands/github
          link: https://github.com/gahaalt

plugins:
    - search
    - autorefs
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    docstring_style: numpy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
    name: material
    palette:
        # Palette toggle for light mode
        -   scheme: default
            primary: white
            accent: deep purple
            toggle:
                icon: material/weather-night
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   scheme: slate
            primary: black
            accent: purple
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode

extra_javascript:
# Read the Docs requires JQuery for its JavaScript code to inject the flyout menu.
# Material for MkDocs does not come with JQuery.
- 'https://code.jquery.com/jquery-3.6.1.min.js'
